### ISSUE TITLE
New Maintainer Wanted :-)

### ISSUE THREAD

**Issue by maelle** [ropensci/wikitaxa#20]
Or new maintainer team. :smile_cat: 

If you're interested, please comment in the issue.
For more info, see
- [our guidance on Changing package maintainers](https://devguide.ropensci.org/changing-maintainers.html);
- [our Package Curation Policy](https://devguide.ropensci.org/curationpolicy.html).

**Comment by maelle** [comment]
Cc @zachary-foster as this package is a dependency of taxize.

**Comment by zachary-foster** [comment]
Thanks for the heads up. I am not sure I would have time to maintain this, but since I maintain taxize it would make sense. I can do it if no one else wants to, but I might have to pass it off to someone else in the future depending on the amount of free time I have.

**Comment by maelle** [comment]
Ok, let's see if someone else wants to (co)maintain this -- feel free to share in your network too. Thank you!

**Comment by maelle** [comment]
@ropensci/admin

**Comment by gsapijaszko** [comment]
Hi @maelle , @zachary-foster 

volunteering to step in and (co)maintain the package.

Regards,
Grzegorz

**Comment by maelle** [comment]
@gsapijaszko thank you!! I've invited you to a team with admin access to this repo, note you'll need to have enabled 2FA for your account, see https://docs.github.com/en/authentication/securing-your-account-with-two-factor-authentication-2fa/configuring-two-factor-authentication and https://ropensci.org/blog/2022/05/16/requiring-2fa-for-the-ropensci-github-organization/

@zachary-foster @gsapijaszko I'll let you both discuss collaboration. :smile_cat:

**Comment by zachary-foster** [comment]
Great, thanks!

**Comment by gsapijaszko** [comment]
@maelle @yabellini grzegorz(at)sapijaszko.net :).

Thanks,
Grzegorz

**Comment by maelle** [comment]
@zachary-foster @gsapijaszko could you please update the DESCRIPTION file? Both of you can be authors but only one can be listed as maintainer :-) Thank you!

**Comment by maelle** [comment]
Hello @zachary-foster @gsapijaszko! Has a decision been reached? And Happy New Year!!

**Comment by zachary-foster** [comment]
I can do it, but it appears I do not have write permissions on this repo yet.

**Comment by maelle** [comment]
@zachary-foster invite now sent! :smile_cat:
