### ISSUE TITLE
Missing common names for wt_wikispecies_parse()

### ISSUE THREAD

**Issue by amauryt** [ropensci/wikitaxa#21]
Hi, thanks for this useful package. A few months ago I created a script with `wt_wikispecies()` that downloaded the common names of certain species without a problem. However, recently I wanted to update this list and realized that common names are no longer parsed.

I suspect that there has been a structure change in the response and that the current selector in the [parsing of vernacular names](https://github.com/ropensci/wikitaxa/blob/263de52d2dcef8762fe458894744cb183cbed86f/R/wikispecies.R#L65) does not work anymore, but I'm not familiar enough with the code to verify at the moment.

My `sessionInfo()`:

```
R version 4.4.1 (2024-06-14)
Platform: x86_64-apple-darwin20
Running under: macOS Sonoma 14.6.1

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.4-x86_64/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.0

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: Europe/Rome
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] wikitaxa_0.4.0.91  data.table_1.16.99

loaded via a namespace (and not attached):
 [1] utf8_1.2.4        R6_2.5.1          httpcode_0.3.0    magrittr_2.0.3    crul_1.5.0        glue_1.7.0       
 [7] urltools_1.7.3    stringr_1.5.1     tibble_3.2.1      pkgconfig_2.0.3   lifecycle_1.0.4   xml2_1.3.6       
[13] cli_3.6.3         fansi_1.0.6       vctrs_0.6.5       snakecase_0.11.1  compiler_4.4.1    purrr_1.0.2      
[19] rstudioapi_0.16.0 tools_4.4.1       curl_5.2.3        pillar_1.9.0      Rcpp_1.0.13       jsonlite_1.8.9   
[25] rlang_1.1.4       triebeard_0.4.1   stringi_1.8.4    
```

**Comment by gsapijaszko** [comment]
Hi @amauryt,

I have addressed it within fork [gsapijaszko/wikitaxa](https://github.com/gsapijaszko/wikitaxa), could you test it on your side, please? 

Before:

``` r
r <- wikitaxa::wt_wikispecies(name = "Cynodon dactylon")
r$common_names
#> # A tibble: 0 × 0
```

and after:

``` r
r <- wikitaxa::wt_wikispecies(name = "Cynodon dactylon")
r$common_names
#> # A tibble: 8 × 2
#>   name                     language
#>   <chr>                    <chr>   
#> 1  Hundszahngras           Deutsch 
#> 2  Bermuda Grass           English 
#> 3  Varvasheinä, sormiheinä suomi   
#> 4  Chiendent pied de poule français
#> 5  Արվանտակ, շնատամ, սիլ   հայերեն 
#> 6  Gramigna                italiano
#> 7  Cynodon palczasty       polski  
#> 8  அறுகு                   தமிழ்
```

<sup>Created on 2024-10-07 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

If/when you confirm it works, I will open pull request.

Regards,
Grzegorz

**Comment by gsapijaszko** [comment]
Fix merged, `test/fixtures` files refreshed, issue closed.

Regards,
Grzegorz

**Comment by amauryt** [comment]
Thanks you @gsapijaszko! I've just confirmed that the fix solved the issue.
